### ISSUE TITLE
32b support

### ISSUE THREAD

**Issue by gregtatcam** [mirage/ocaml-git#105]
run 'ogit clone --bare remote-repo local-repo', then cd to local-repo and run 'git reset master --hard'. Get errors:

error: wrong index v2 file size in .git/objects/pack/pack-88a6bbf29934073da5deb72f2baadacd365dcda9.idx
error: wrong index v2 file size in .git/objects/pack/pack-88a6bbf29934073da5deb72f2baadacd365dcda9.idx
fatal: Could not parse object 'master'.

Git version 1.6.2.

**Comment by samoht** [comment]
Is it easily reproducible? Which remote repo? Did you set up a depth parameter?

**Comment by gregtatcam** [comment]
it happens with just one file in the repository. It only happens on rPi. I didn't set the depth.
- create a repo
 git init repo; cd repo; echo "a" > a; git add -A; git commit -m "a"
- run daemon
 git daemon --export-all --reuseaddr --base-path=/ /
- clone
 ogit clone --bare repo 
I compared .git/index and .git/objects/pack/*.idx on MAC and rPi and they are different. I can send tar of the repo if it helps.

**Comment by gregtatcam** [comment]
I built 32-bit Ubuntu 15.04 for Virtual Box. The issue is reproducible on this system. I can provide the image.

**Comment by samoht** [comment]
Thanks for the report! I looks like a 64b overflow in the sizes/offsets handling in the pack file. Should be easy to fix.

**Comment by gregtatcam** [comment]
Great!

**Comment by samoht** [comment]
This is actually a bit harder than I though, as it might need a custom layer on top of bigarrays to deal with large files (both cstruct and mstruct do not work well on 32b platforms it seems...)

**Comment by samoht** [comment]
See https://github.com/mirage/ocaml-cstruct/issues/71
