### ISSUE TITLE
ERROR while installing git.1.6.2

### ISSUE THREAD

**Issue by talex5** [mirage/ocaml-git#116]
Travis is complaining again that it can't install ocaml-git (needed to compile CueKeeper):

https://travis-ci.org/talex5/cuekeeper/builds/74039624

    #=== ERROR while installing git.1.6.2 =========================================#
    # opam-version 1.2.2
    # os           linux
    # command      make test
    # path         /home/travis/.opam/system/build/git.1.6.2
    # compiler     system (4.02.1)
    # exit-code    2
    # env-file     /home/travis/.opam/system/build/git.1.6.2/git-35650-a3393d.env
    # stdout-file  /home/travis/.opam/system/build/git.1.6.2/git-35650-a3393d.out
    # stderr-file  /home/travis/.opam/system/build/git.1.6.2/git-35650-a3393d.err
    ### stdout ###
    # [...]
    [ERROR]     MIR-FS-mirage  1   Operations on trees.
    [ERROR]     MIR-FS-mirage  2   Operations on commits.
    [ERROR]     MIR-FS-mirage  3   Operations on tags.
    [ERROR]     MIR-FS-mirage  4   Operations on references.
    [ERROR]     MIR-FS-mirage  5   Operations on index.
    [OK]        MIR-FS-mirage  6   Operations on pack files.
    [SKIP]      MIR-FS-mirage  7   Resource leaks.
    [SKIP]      MIR-FS-mirage  8   Basic Remote operations.
    [SKIP]      MIR-FS-mirage  9   Cloning ocaml-git.git.
    # 6 errors! in 0.550s. 22 tests run.
    ### stderr ###
    # W: Cannot find source file matching module 'git' in library git
    # W: Test 'test_git' fails: Command '/home/travis/.opam/system/build/git.1.6.2/_build/lib_test/test.native -q' terminated with error code 6
    # E: Failure("Tests had a 100.00% failure rate")
    # make: *** [test] Error 1

I also tried using the Git version of ocaml-git, but that fails with `Unbound record field Git.Sync.Result.references`.

**Comment by samoht** [comment]
This is due to a change in semantics in mirage-fs-unix. I've updated the constraints in opam-repository and I the Git version is updated to work fine with the latest version of mirage-fs-unix. I'll update Irmin once I've done breaking ocaml-git's API.
