### ISSUE TITLE
ERROR while installing git.1.6.2 (IO.t)

### ISSUE THREAD

**Issue by talex5** [mirage/ocaml-git#117]
Here's another one:

https://travis-ci.org/talex5/cuekeeper/builds/74237273

    #=== ERROR while installing git.1.6.2 =========================================#
    # opam-version 1.2.2
    # os           linux
    # command      make
    # path         /home/travis/.opam/system/build/git.1.6.2
    # compiler     system (4.02.1)
    # exit-code    2
    # env-file     /home/travis/.opam/system/build/git.1.6.2/git-35854-899f4c.env
    # stdout-file  /home/travis/.opam/system/build/git.1.6.2/git-35854-899f4c.out
    # stderr-file  /home/travis/.opam/system/build/git.1.6.2/git-35854-899f4c.err
    ### stdout ###
    # [...]
    # + /home/travis/.opam/system/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -package compiler-libs.toplevel -w A-4-41-44 -I lib/top -o lib/top/git_top.cmx lib/top/git_top.ml
    # findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /usr/lib/ocaml, /usr/lib/ocaml/compiler-libs
    # /home/travis/.opam/system/bin/ocamlfind ocamlopt -a lib/top/git_top.cmx -o lib/top/git_top.cmxa
    # /home/travis/.opam/system/bin/ocamlfind ocamlopt -shared lib/top/git_top.cmxa lib/top/git_top.cmx -o lib/top/git_top.cmxs
    # /home/travis/.opam/system/bin/ocamlfind ocamldep -package cohttp.lwt -package dolog -package hex -package lwt -package mstruct -package nocrypto -package ocamlgraph -package stringext -package uri -package uri.services -package zip -modules lib/http/git_http.mli > lib/http/git_http.mli.depends
    # /home/travis/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I lib -package cohttp.lwt -package dolog -package hex -package lwt -package mstruct -package nocrypto -package ocamlgraph -package stringext -package uri -package uri.services -package zip -w A-4-41-44 -I lib/http -I lib -o lib/http/git_http.cmi lib/http/git_http.mli
    # + /home/travis/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I lib -package cohttp.lwt -package dolog -package hex -package lwt -package mstruct -package nocrypto -package ocamlgraph -package stringext -package uri -package uri.services -package zip -w A-4-41-44 -I lib/http -I lib -o lib/http/git_http.cmi lib/http/git_http.mli
    # File "lib/http/git_http.mli", line 47, characters 10-60:
    # Error: The signature constrained by `with' has no component named IO.t
    # Command exited with code 2.
    ### stderr ###
    # W: Cannot find source file matching module 'git' in library git
    # E: Failure("Command ''/usr/bin/ocamlbuild' lib/git.cma lib/git.cmxa lib/git.a lib/git.cmxs lib/top/git_top.cma lib/top/git_top.cmxa lib/top/git_top.a lib/top/git_top.cmxs lib/http/git-http.cma lib/http/git-http.cmxa lib/http/git-http.a lib/http/git-http.cmxs lib/unix/git-unix.cma lib/unix/git-unix.cmxa lib/unix/git-unix.a lib/unix/git-unix.cmxs lib/mirage/git-mirage.cma lib/mirage/git-mirage.cmxa lib/mirage/git-mirage.a lib/mirage/git-mirage.cmxs bin/ogit.native -tag debug' terminated with error code 10")
    # make: *** [build] Error 1

**Comment by samoht** [comment]
need a constraint on the version of cohttp...

**Comment by talex5** [comment]
Yeah, I added one to my test branch: https://github.com/talex5/ocaml-git/commit/10ae0a1a489a04536e09832d01b10c3841e65a18

Now Travis is failing on the tcpip tests instead (`iperf test timed out after 120.000000 seconds`) :-/ https://travis-ci.org/talex5/cuekeeper/builds/74240835

**Comment by samoht** [comment]
See https://github.com/ocaml/opam-repository/pull/4607

For the other failure, @Magnusm would it be possible to avoid these timeouts? (maybe using a different Clock implementation, as @yomimono did for arp)

**Comment by MagnusS** [comment]
@samoht Hm - I'm not sure if speeding up the clock would help. As Travis' performance varies a lot it's difficult to find a good value for the timeout. I could change the test to only timeout if the connection has stalled completely for the timeout duration - maybe that will work better with very slow Travis instances.

**Comment by talex5** [comment]
Do we need a physical clock at all? Why not use a virtual clock, that doesn't depend on the real time the tests take?

BTW, I restarted the build, so I'll copy the error here in case we need it:

    #=== ERROR while installing tcpip.2.6.0 =======================================#
    # opam-version 1.2.2
    # os           linux
    # command      make test TESTFLAGS=-v
    # path         /home/travis/.opam/system/build/tcpip.2.6.0
    # compiler     system (4.02.1)
    # exit-code    2
    # env-file     /home/travis/.opam/system/build/tcpip.2.6.0/tcpip-35867-62756b.env
    # stdout-file  /home/travis/.opam/system/build/tcpip.2.6.0/tcpip-35867-62756b.out
    # stderr-file  /home/travis/.opam/system/build/tcpip.2.6.0/tcpip-35867-62756b.err
    ### stdout ###
    # [...]
    [ERROR]     iperf    2   iperf with two stacks and uniform packet loss.
    [SKIP]      iperf    3   iperf with two stacks, basic tests, longer.
    [SKIP]      iperf    4   iperf with two stacks and uniform packet loss, longer.
    # -- iperf.002 Failed --
    # iperf with two stacks and uniform packet loss.
    # ./_tests/iperf.002.output:
    # --
    # [exception] OUnitTest.OUnit_failure("iperf test timed out after 120.000000 seconds")
    # 
    # 1 error! in 1.047s. 17 tests run.

**Comment by MagnusS** [comment]
No, it could be virtual. But we need a way to detect if the connection has stalled.

**Comment by talex5** [comment]
We could still have the 120s timeout, but they'd be virtual seconds, so not affected by the load on the machine running the tests (I'm assuming that's the cause).
