### ISSUE TITLE
undefined reference to `crc32_string' under Xen

### ISSUE THREAD

**Issue by talex5** [mirage/ocaml-git#127]
Compiling for Irmin/git under Xen now gives:

    _build/main.native.o: In function `camlCrc__cstruct_1022':
    /home/user/.opam/4.01.0/build/crc.0.9.0/_build/lib/crc.ml:42: undefined reference to `crc32_cstruct'
    _build/main.native.o: In function `camlCrc__string_1027':
    /home/user/.opam/4.01.0/build/crc.0.9.0/_build/lib/crc.ml:46: undefined reference to `crc32_string'
    _build/main.native.o: In function `camlCrc__4':
    (.data+0x138ee0): undefined reference to `crc32_string'
    _build/main.native.o: In function `camlCrc__4':
    (.data+0x138ee8): undefined reference to `crc32_cstruct'

I assume we're just missing some Xen stubs for crc. Do you have a patched version?

**Comment by samoht** [comment]
Hum I though I had this somewhere but I can't find it anymore...

**Comment by talex5** [comment]
OK, quick hack here: https://github.com/talex5/ocaml-crc/tree/xen

**Comment by hannesm** [comment]
this is fixed in upstream crc (since 1.0.0 -- see https://github.com/xapi-project/ocaml-crc/commit/a1a0bc64cc38a115424e6184d77d35b49f73db94)

**Comment by g2p** [comment]
I have the same error on ukvm.

**Comment by hannesm** [comment]
@g2p surely crc needs - similar to the xen_linkopts - some solo5_linkopts magic and compile the C stubs with the correct CFLAGS for solo5.  Is there a general solution on the horizon? @avsm or @pqwy may know...
