### ISSUE TITLE
Expose SHA.digest_size

### ISSUE THREAD

**Issue by samoht** [mirage/ocaml-git#128]

**Comment by dinosaure** [comment]
From #227, the `Hash` module available in the common API between memory back-end and file-system back-end is constrained by an equality with the `Hash` argument functor, which has this signature:

```ocaml
module type IDIGEST =
sig
  type t
  type ctx
  type buffer

  val init   : unit -> ctx
  val feed   : ctx -> buffer -> unit
  val get    : ctx -> t

  val length : int
end

module type HASH =
sig
  include BASE

  module Digest : IDIGEST with type t = t

  val get : t -> int -> char

  val to_string : t -> string
  val of_string : string -> t

  type hex

  val to_hex : t -> hex
  val of_hex : hex -> t
end
```

That means, all of these operations is available (including `Hash.Digest.length`) from an already applied Git Store functor (like `MyStore.Hash.Digest.length`).

**Comment by samoht** [comment]
Fixed in master.
