### ISSUE TITLE
Removing a branch silently fails

### ISSUE THREAD

**Issue by talex5** [mirage/ocaml-git#153]
In https://github.com/mirage/ocaml-git/blob/b21bf26b0deac7cf42d11e7f3e66f54a91241ea4/lib/FS.ml#L522 we have:

```
  let remove_reference t ref =
    let file = file_of_ref t ref in
    Lwt.catch
      (fun () -> IO.remove file)
      (fun _ -> Lwt.return_unit)
```

If the process doesn't have permission to remove the file (e.g. because it's running as the wrong user) then this will appear to succeed, but the branch will reappear in future.

**Comment by talex5** [comment]
However, this wasn't the cause. In fact, the ref was stored in `packed-refs` and `info/refs`, but ocaml-git only tries to remove `t.dot_git / Reference.to_raw ref` (`.git/refs/heads/$branch_name`).

**Comment by dinosaure** [comment]
Should be fixed with https://github.com/mirage/ocaml-git/blob/master/src/git/store.ml#L988 which looks into `packed-refs` to delete reference.
