### ISSUE TITLE
ENOENT statting branch lock file

### ISSUE THREAD

**Issue by talex5** [mirage/ocaml-git#157]
I saw DataKit die once with:

```
Fatal error: exception Unix.Unix_error(Unix.ENOENT, "stat", "/Users/tal/.../.git/refs/heads/github-metadata.lock")
```

I was probably editing the repository with the Git tools at the time. Not sure what's accessing the lock file in ocaml-git (maybe just scanning for refs or something?).

**Comment by samoht** [comment]
The lock file is supposed to be in a separate directory to avoid this kind of issue. Not sure where this regression comes from (I am pretty sure I have fixed that few years ago already :p)

**Comment by talex5** [comment]
I guess C git created the lock file, but we shouldn't crash.

**Comment by samoht** [comment]
no more lock files in ocaml-git 2.0
