### ISSUE TITLE
Can not read a SHA1 that was found by the lib itself!

### ISSUE THREAD

**Issue by jnavila** [mirage/ocaml-git#159]
Here a minimal code example that shows what I'm talking about:

```ocaml
open Lwt.Infix
open Git_unix
module Search = Git.Search.Make(FS)

let fs = FS.create ()

let find_libs ref =
  fs >>= fun t ->
  ref >>= fun h ->
  Search.find t h (`Path []) >>= function
  | None     -> failwith "path not found"
  | Some sha ->
     FS.read t sha >|= function
     | Some Git.Value.Tree t -> Git.Tree.pp Fmt.stdout t;find_cache_libs t
     | Some a -> Git.Value.pp Fmt.stdout a;failwith "not a tree!"
     | None -> Git.Hash.pp Fmt.stdout sha; failwith "sha not found"

let rev_parse r =
  Lwt_process.pread ("", [|"git" ;"rev-parse"; r|]) >|= (fun s ->
  Git.Hash.of_raw(Str.first_chars s 40))

let ()=
  Lwt_main.run @@ rev_parse "master" >>= find_libs
```

This fails with "sha not found"

**Comment by samoht** [comment]
```
Git.Hash.of_raw(Str.first_chars s 40))
```

This looks very suspicious to me. I think you want to use `Git.Hash.of_hex`

**Comment by jnavila** [comment]
`Git.Hash.of_hex` does not exist.  That's the best way I found.

Anyway, my point is that the code breaks on the second step of the code in `FS.read` where the first search was already processed and yielded a `Git.Hash.t`, which basically should mean that the first Hash was found and the path for this SHA1 exists.

**Comment by samoht** [comment]
The missing `of_hex` is a regression, I will add it back, thanks for spotting this!

Unfortunately I cannot compile your code snippet. Would be useful to have a working repro to investigate a bit more.

```
$  ocamlfind ocamlopt -package git foo.ml -o foo
 line 14, characters 56-71:
Error: Unbound value find_cache_libs
[.. and other errors after fixing this one ... ]
```

**Comment by jnavila** [comment]
You can find the original code at my repo jnavila/plotkicadsch on the branch `OnLwt`

**Comment by samoht** [comment]
Hum I am clearly not very awake tonight. The `of_hex` is still there, but need a bit more glue code.

```
let of_hex = Git_unix.Hash_IO.of_hex
```

I will check your branch, thanks for the report.

**Comment by samoht** [comment]
The code for find is the [following](https://github.com/mirage/ocaml-git/blob/master/lib/git_search.ml#L68):

```ocaml
  let rec find t hash path =
    match path with
    | `Path []   -> Lwt.return (Some hash)
  [...]
```

which means that in your case, it doesn't even do a proper lookup in the filesystem. I guess you didn't save the object on the disk before doing the lookup.

btw, `ocaml-git` is very low-level (as you might have guessed already), so you might want to have a look at [Irmin](https://github.com/mirage/irmin) instead to write/read in Git more easily.

**Comment by jnavila** [comment]
Ah. Thanks for the heads up. I'll look into Irmin if it can simplify the code.
