### ISSUE TITLE
undefined reference to `crc32_string' under Solo5

### ISSUE THREAD

**Issue by g2p** [mirage/ocaml-git#165]
Building https://github.com/g2p/irc-unikernel/tree/fat-test-case fails with the ukvm target

```
_build/main.native.o : Dans la fonction « camlCrc__3 » :
lib/crc.ml:(.data+0xbdb48) : référence indéfinie vers « crc32_string »
lib/crc.ml:(.data+0xbdb50) : référence indéfinie vers « crc32_cstruct »
```

This is #127 with the Solo5 backend. Creating a new issue so it doesn't get lost.

**Comment by g2p** [comment]
Given the complexity of the ocaml-crc build system, which is much larger than the implementation, would a PR removing the dependency on ocaml-crc and switching to a pure OCaml implementation be considered?

**Comment by samoht** [comment]
@g2p yes please!

**Comment by g2p** [comment]
Since nocrypto already has C code and a portable build, would it be acceptable to add an accelerated implementation there?

**Comment by hannesm** [comment]
I'd rather have a standalone library with crc (and maybe adler and other checksum algorithms).  nocrypto is IMHO already too broad and big (by providing asymmetric and symmetric ciphers, as well as RNG, and also hash algorithms)..
