### ISSUE TITLE
Unable to pull repository from Github in Canopy

### ISSUE THREAD

**Issue by gjaldon** [mirage/ocaml-git#205]
I'm trying to run latest master of Canopy on my local machine (Arch Linux) and I keep getting errors when pulling the repo from Github. Below are the errors I get:

The error below is already reported at https://github.com/mirage/ocaml-git/issues/138
https://gist.github.com/gjaldon/83985d294ef724568a35d092726daee5/

When trying the work-around proposed by @hannesm to use `git` instead of `https`, I get the error below:
https://gist.github.com/gjaldon/52808e7b21c8776c9f599be0900bc6da

**Comment by gjaldon** [comment]
Update: this error also happens on MacOs.

**Comment by dinosaure** [comment]
From what I know, in `master`, `dune exec -- ogit-http-clone https://github.com/hannesm/canopy-data.git` works.
