### ISSUE TITLE
Streaming API

### ISSUE THREAD

**Issue by samoht** [mirage/ocaml-git#33]
Would be nice if we can get the core binary format having a streaming interface. I don't have a clear idea of what it would look like, but that could be useful to have a Git codec that you can easily compose with others (such as Xmlm et Jsonm).

**Comment by samoht** [comment]
Would be interesting to see if https://github.com/inhabitedtype/angstrom is a good fit here. /cc @seliopou

**Comment by seliopou** [comment]
Should be a good fit. I'm not too familiar with the git protocol, but it should be possible to write git, json, and xml parsers independently and compose them together in whatever way you see fit.

**Comment by samoht** [comment]
The disk format is relatively simple: https://github.com/mirage/ocaml-git/blob/master/doc/protocol.txt
the on-wire format too: https://github.com/mirage/ocaml-git/blob/master/doc/pack-protocol.txt

Would be great if could also write things using the same instead of just parsing, but I guess it is not in scope with angstrom

**Comment by dinosaure** [comment]
Done by #227

**Comment by samoht** [comment]
#227 is now merged in master.
