### ISSUE TITLE
No such package: `git.unix`

### ISSUE THREAD

**Issue by abhillman** [mirage/ocaml-git#332]
Having a bit of trouble. After successfully running `opam install git`, I am getting the following:

```
utop # #require "git.unix";;
No such package: git.unix
```

Any guidance? Could this be a bug?

**Comment by dinosaure** [comment]
We probably need to run `opam install git-unix`.

**Comment by shonfeder** [comment]
What does seem to work (for me) is `#require "git-unix";;`

**Comment by dinosaure** [comment]
Should be fixed by #383
