### ISSUE TITLE
Heads-up: lru.0.3.0 breakage

### ISSUE THREAD

**Issue by pqwy** [mirage/ocaml-git#352]
[Lru.0.3.0](https://github.com/ocaml/opam-repository/pull/13864) breaks the API: bindings need to be explicitly promoted, and the map needs to be explicitly trimmed. The change is mostly search-and-replace.

**Comment by dinosaure** [comment]
According CHANGES, I just need to put a constraint on your package. So, I'm waiting merge of your release on opam-repository. Thanks :+1: .
