### ISSUE TITLE
Finish the switch to lru.0.3.0

### ISSUE THREAD

**Issue by pqwy** [mirage/ocaml-git#357]
One certain, one potential performance bug:

- [`add`](https://github.com/dinosaure/ocaml-git/blob/14d12562d52ec3b2467a33ad7238d9ad3993cf2e/src/git/pack.ml#L808) needs a corresponding [`trim`](https://pqwy.github.io/lru/doc/lru/Lru/F/module-type-S/index.html#val-add).
- If the order is irrelevant, this [`fold`](https://github.com/dinosaure/ocaml-git/blob/14d12562d52ec3b2467a33ad7238d9ad3993cf2e/src/git/pack.ml#L676) should be a [`fold_k`](https://pqwy.github.io/lru/doc/lru/Lru/F/module-type-S/index.html#val-fold).

I know... sorry for the breakage!

**Comment by dinosaure** [comment]
Done by #358, thanks!

**Comment by pqwy** [comment]
Ordering in there _is_ important? What's the typical `size` of `window`?

**Comment by dinosaure** [comment]
Yes, it's an heuristic used by `git` in general where we should apply `duff`/`libXdiff` with a better ratio with the most recently element added in the Window. `size` is 10 according to `git`.

**Comment by pqwy** [comment]
*The order of `fold` changed.* Right?

**Comment by dinosaure** [comment]
According to your CHANGES:

> F.S.fold and F.S.iter iterate in LRU order.

If you mean that `fold` apply `f` to the most recent element firstly, this is what we want.

**Comment by pqwy** [comment]
[I'm not sure what's first/last here so it might be going in the wrong direction, but that's the right axis](https://pqwy.github.io/lru/doc/lru/Lru/F/module-type-S/index.html#val-fold).

I think adding a test for this would be a good idea. Because if that ordering does matter, this code is either broken now, of has been until now.

**Comment by dinosaure** [comment]
Ok, I will investigate and try to make a regression test of what I really expect about this part :+1: .

**Comment by dinosaure** [comment]
`lru` is not used anymore by `ocaml-git`.
