### ISSUE TITLE
Release of 2.1.0

### ISSUE THREAD

**Issue by dinosaure** [mirage/ocaml-git#361]
Even if #357 or ownership bug on KVM, it should be possible to make a new release where we fix several bugs and remove blocker to release `irmin.2.0.0`. @mirage/core?

**Comment by samoht** [comment]
I think it's fine to delay the release a bit -- it's not good to release something with known bugs.

**Comment by dinosaure** [comment]
When I locally deploy an unikernel with Canopy from example and from contents of @hannesm without any error (about `ocaml-git`), we should start to prepare a release of it I think.

**Comment by samoht** [comment]
That's be great! That's the only non-released package for irminv2 :-)

**Comment by avsm** [comment]
now released!
