### ISSUE TITLE
ogit binary?

### ISSUE THREAD

**Issue by ursetto** [mirage/ocaml-git#368]
Unless I'm overlooking something, the `ogit` binary appears to have been removed way back in commit 4d712f862ee82cb676eb5e098cef7e7be79461ba, and replaced with a few binaries called `ogit-*`. It's not clear why from the commit message.

If this is gone, should it be removed from the front page README.md?

**Comment by dinosaure** [comment]
As I just wrote on the `README.md`, binaries are just examples of `ocaml-git` - so we don't want to maintain them as real user tools, or, in other words, it's not the goal of __this__ repository. Thanks for you note :+1: .
