### ISSUE TITLE
Be resilient about remote empty Git repository

### ISSUE THREAD

**Issue by dinosaure** [mirage/ocaml-git#397]
The previous version of `ocaml-git` does not complain when it wants to be synchronise with a non-existing reference. Logically, the point is valid - try to `git fetch` an empty repository returns an error. However, it breaks an expected old behavior of `ocaml-git`. We can silently do nothing when the reference does not exist remotely.

**Comment by hannesm** [comment]
This would be great to have dealt with before a release. It would be great to have a path with git (+irmin-git) from a completely empty git repository to a working irmin-mirage-git.KV_RW. With the current state, I don't seem to get `Git_store.connect` (which does the initial clone) to work, which is a prerequisite for a commit (with `module Git_store = Irmin_mirage_git.KV_RW(Irmin_git.Mem)(Pclock)`).

Thanks for your work.

**Comment by dinosaure** [comment]
With #412 and this code:
```ocaml
module Git = Irmin_git.Mem
module Sync = Irmin_mirage_git.KV_RW(Irmin_git.Mem)(Pclock)

open Lwt.Infix

let resolve v =
  Fmt.epr "[-] resolve %s.\n%!" (Conduit.Endpoint.to_string v) ;
  Conduit_lwt.TCP.resolve ~port:9418 v

let tcp_protocol = Conduit_mirage.register ~protocol:(module Conduit_lwt.TCP.Protocol)

let resolvers =
  Conduit.empty
  |> Conduit_mirage.add tcp_protocol resolve

let run () =
  Git.v (Fpath.v ".") >>= function
  | Error err -> Fmt.failwith "%a" Git.pp_error err
  | Ok store ->
    Fmt.epr "[-] Start connect to git://localhost/test.\n%!" ;
    Sync.connect ~resolvers store "git://127.0.0.1/test" >>= fun _ ->
    Fmt.epr "[-] Repository cloned!\n%!" ;
    Lwt.return_unit

let () = Lwt_main.run (run ())
```

I'm able to "clone" an empty Git repository. My old version of me already did some tests about empty Git repository and we correctly return a simple `Empty` PACK file. One the Irmin side, it seems that all is correct, just an error log appear but the process does not fail and it does not return an error. However, a slightly detail must be explained here which is about the new version of `conduit`.

`Irmin_mirage_git` currently uses `Conduit_mirage`. By types, `Conduit_mirage` and `Conduit_lwt` are the same (hence my possibility to register `Conduit_lwt.TCP.Protocol` as a _Mirage protocol_). However, by values, they are not the same and try to fill the `resolvers` with `Conduit_lwt` instead of `Conduit_mirage` is like a _no-operation_. Deeply in the stack, `Conduit_mirage.resolve` will see a `lwt`'s resolver (and not a `mirage`'s resolver) and [it will just ignore it](https://github.com/mirage/ocaml-conduit/blob/e0565d08f823210850cb2519c139add5aeda890a/src/core/conduit.ml#L393-L395).

It's why in this context, I use `Conduit_mirage.add` (although it is possible to use `Conduit_lwt.add`). In my head, such usage should never append where `Conduit_lwt` and `Conduit_mirage` should not be co-usable - but in this small piece of code, it was the case...
