### ISSUE TITLE
I don't see git output anymore

### ISSUE THREAD

**Issue by hannesm** [mirage/ocaml-git#409]
with a recent master (792751dc689c6593efd515dfffb9f1722c6c2f53), I don't see any git output anymore in the logs (using git via irmin-mirage-git). previously I saw log messages.

I think the `push_stdout` and `push_stderr` need to be bound for such a use-case, but I'm unsure where. The package `git-mirage` is completely empty (and could be removed). I'm not sure whether irmin-git.ml is the right place:

```diff
@@ -769,7 +769,10 @@ struct
     let capabilities =
       [ `Side_band_64k; `Multi_ack_detailed; `Ofs_delta; `Thin_pack
       ; `Report_status ] in
-    S.fetch ~capabilities ~resolvers e t (`Some [ reference ]) >>= function
+    let push_stdout msg = Log.info (fun f -> f "git %s" msg)
+    and push_stderr msg = Log.warn (fun f -> f "git %s" msg)
+    in
+    S.fetch ~push_stdout ~push_stderr ~capabilities ~resolvers e t (`Some [ reference ]) >>= function
     | Error `Not_found -> Lwt.return (Error (`Msg "not found"))
     | Error (`Msg err) -> Lwt.return (Error (`Msg err))
     | Error (`Exn err) -> Lwt.return (Error (`Msg (Printexc.to_string err)))
```

Would be nice to have this sorted out before a release.

**Comment by dinosaure** [comment]
I think `irmin-git` is the right place for that :+1:.

**Comment by hannesm** [comment]
ok, done in https://github.com/dinosaure/irmin/pull/4/commits/243797ae6ab029871415702def72b52fd79a8562 (see https://github.com/dinosaure/irmin/pull/4) -- but not tested

**Comment by dinosaure** [comment]
Thanks!
