### ISSUE TITLE
Support for shallow objects

### ISSUE THREAD

**Issue by samoht** [mirage/ocaml-git#45]
A git repository can have `shallow` objects, ie. references to objects not present in the local repostiory. This could be quite useful for partial clones although this also introduces some difficulties while synchronising two repositories with shallow objects.

**Comment by samoht** [comment]
Although we now support shallow packs (since 1.5.2), shallow objects are different as they need a specific file to be present in `.git/shallow`, see https://github.com/git/git/blob/master/Documentation/technical/shallow.txt

**Comment by samoht** [comment]
shallow packs are not fully supported.

**Comment by hannesm** [comment]
IIUC #402 implements this.
