### ISSUE TITLE
git example unikernel: abstract using rsa and ed25519 keys

### ISSUE THREAD

**Issue by hannesm** [mirage/ocaml-git#482]
At the moment, this is hardcoded to rsa in mimic. It would be nice to have a boot flag whether a rsa or a ed25519 key is to be used. Eventually it makes sense to rethink the key seed & keytype argument into a single "ed25519:<key>" / "rsa:<seed>"... same for the authenticator (which is the ssh fingerprint but does not include the key type (there's Awa.Keys.authenticator_of_string which includes the type)).

Maybe Awa should provide a sensible interface first how to deserialise a ssh key (from seed / direct), similar to authenticator?

**Comment by dinosaure** [comment]
This issue is closed by the `Awa.Keys.of_string`
