### ISSUE TITLE
FAIL Git.Store.read_inflated fails on s390x

### ISSUE THREAD

**Issue by tmcgilchrist** [mirage/ocaml-git#524]
Possibly related to https://github.com/mirage/ocaml-git/issues/521

Another s390 git related build failure, seems to emanate from `Git.Store.read_inflated`. I can’t reproduce on x86 trying on linux/ppc32 (which is the other Big Endian system I've access to).

```
test.exe: [INFO] Created new log file at
                 /src/_build/default/test/var/job/2021-07-29/060517-test_analyse-simple-313552.log
test.exe: [INFO] Exec: "git" "init"
test.exe: [INFO] Exec: "git" "add" "."
test.exe: [INFO] Exec: "git" "commit" "-m" "init"
test.exe: [INFO] Exec: "git" "rev-parse" "HEAD"
test.exe: [INFO] Exec: "git" "clone" "--bare" "opam-repository-builder" 
                       "opam-repository"
test.exe: [INFO] Exec: "find" "." "-maxdepth" "3" "-name" "*.opam"
2021-07-29 07:05.17      git.store [ERROR] Object 51f71a76093c11455bf7e9f8c61fb526c998c842 not found.
solver bug: (Invalid_argument
  "Git.Store.read_exn: 51f71a76093c11455bf7e9f8c61fb526c998c842 not found")
Fatal error: exception (Invalid_argument
  "Git.Store.read_exn: 51f71a76093c11455bf7e9f8c61fb526c998c842 not found")
Raised at Dune__exe__Solver.main in file "solver/solver.ml", line 90, characters 4-12
Called from Dune__exe__Main in file "solver/main.ml", line 54, characters 37-82
```
https://ci.ocamllabs.io/github/ocurrent/ocaml-ci/commit/ade723dd98d51233593dfc76fcd6583ba8c4aa29/variant/debian-10-4.12_s390x

**Comment by dinosaure** [comment]
Yes, currently `checkseum` is the last dependency where we have a bug on big-endian, I will try to fix that today and ask to you if you can relaunch your test.

**Comment by dinosaure** [comment]
Can you try with https://github.com/mirage/ocaml-git/pull/523? It solve the big-endian support.

**Comment by talex5** [comment]
Tested in https://github.com/ocurrent/ocaml-ci/pull/360 - seems to be working!
