### ISSUE TITLE
Git.Misc functions for bounded parallelism could go upstream

### ISSUE THREAD

**Issue by avsm** [mirage/ocaml-git#54]
These iteration functions over pools are useful for Cohttp as well and could potentially go upstream to Lwt quite nicely (or into a separate Lwt_bounded library might make releases easier):

```
val list_iter_p : ?pool:unit Lwt_pool.t -> ('a -> unit Lwt.t) -> 'a list -> unit Lwt.t
Same as List_lwt.iter_p but using a maximum width equals to the size of the pool. The default width is 50.
val list_map_p : ?pool:unit Lwt_pool.t -> ('a -> 'b Lwt.t) -> 'a list -> 'b list Lwt.t
Same as List_lwt.map_p but using a maximum width equals to the size of pool. The default width is 50.
```

**Comment by samoht** [comment]
Not sure on where to put these, but yes that could be nice to gather similar functions somewhere.

**Comment by dinosaure** [comment]
From #227, it could be possible (and easy) to make a pool to read and write on a git repository. I followed the same convention from Lwt and provide `*_p` functions which need some `Cstruct.t`. So, it could be good to make a `Cstruct.t` pool and use them for any operation in the Git repository.

Currently, #227 provides `*_p` and `*_s`. The last one use already defined internal buffers attached to the Git state.

However, this API is __not__ available in the common API between the memory back-end and the file-system back-end and, of course, it's only available in the file-system back-end (including unix and mirage).
