### ISSUE TITLE
Don't suppose getconf is in PATH at runtime

### ISSUE THREAD

**Issue by Et7f3** [mirage/ocaml-git#599]
For nixpkgs I patched carton so it can find getconf. Do you think you can implement a ./configure like way to check this path ? getconf could be put in `propagatedBuildInput` but this will propagate to all reverse dependencies. Nix prefer to be explicit if possible. This is a low priority issue.

see https://github.com/Et7f3/nixpkgs/blob/e0532dd87c099ddfe20c53c8a2bc860ab6f90355/pkgs/development/ocaml-modules/carton/carton-find-getconf.patch#L9-L10

`Unix.open_process_in` could be replace with `Unix.open_process_args_in` and avoid shell but it is unrelated.

**Comment by dinosaure** [comment]
As you prefer, if you propose a PR, I will happy to integrate it. You should take a look on mirage/ocaml-gmp#18 where the question of: how many core do we have? was specially solved across different platform (including NixOS).

**Comment by Et7f3** [comment]
What about a C solution that works even on windows ?
https://github.com/ocaml/ocaml/blob/28dfeb0f61e96ab7bf1aef77e99d65ae68863416/runtime/domain.c#L1799-L1808

I only a C file benchmark that's why I ask.

**Comment by dinosaure** [comment]
I'm rather inclined to reject C code but since it's ultimately the production of a binary, this may be a good solution indeed.

**Comment by dinosaure** [comment]
Can you confirm that #600 fix the issue?

**Comment by Et7f3** [comment]
I don't see what changed but I no longer get failure related to getconf.

While I tried I see other failure unrelated to the code here (mimic 0.0.6 is not packaged in nixpkgs) so I will close this issue. Thanks for the ping.

Since we have still failure I lets the CI in passive mode (`|| true`)
https://github.com/mirage/ocaml-git/blob/37c9ef41944b5b19117c34eee83ca672bb63f482/.github/workflows/nixos.yml#L26
