### ISSUE TITLE
incorrect `git status`

### ISSUE THREAD

**Issue by samoht** [mirage/ocaml-git#68]
In non-bare repositories, `git status` is incorrect, although `git diff` returns an empty diff. Need to dig more into the index/staging protocol to understand exactly what happens here.

Reported by @gregtatcam.

**Comment by samoht** [comment]
Actually the issue only appears on bare repository (I cannot reproduce it on normal non-bare ones). I'm closing that issue because `git status` is not supposed to be run on bare repository.

The real cause of the issue is a difference in the representation of bare repositories between `git` and `ocaml-git:

- `git` expands the file hierarchy of `.git` inside the parent folder, it keeps the `.git` folder but does not expand the filesystem.  Running `git status` there returns an error ("not a Git repository").

- `ocaml-git` simply uses the same `.git` folder but does not expand the blobs on the filesystem and it doesn't build `.git/index`. So the `git` tool is confused and it things everything has been removed.

**Comment by gregtatcam** [comment]
Cool, thanks.
