### ISSUE TITLE
irmin 0.9.3 build fails when upgrading to git 1.4.11

### ISSUE THREAD

**Issue by gregtatcam** [mirage/ocaml-git#74]
# File "lib/git/irmin_git.ml", line 629, characters 19-25:
# Error: Signature mismatch:
#        ...
#        The type `ctx' is required but not provided

**Comment by samoht** [comment]
yes, it builds with master. I need to make a new release of `irmin` and update the dependency constraints, thanks for the report.

**Comment by gregtatcam** [comment]
Great!

**Comment by samoht** [comment]
See https://github.com/ocaml/opam-repository/pull/3739
