### ISSUE TITLE
shallow pack support

### ISSUE THREAD

**Issue by avsm** [mirage/ocaml-git#81]
When cloning opam-repository with git 1.4.11, I get:
```
Packed_value.to_pic: shallow pack are not supported.
bc74b8ec0cbfb170cadb77b04873219f55836652 is not in the pack file!
```

Code at: https://github.com/avsm/ocaml-docker-scripts/blob/master/bulk-build/generate_index.ml

**Comment by avsm** [comment]
Workaround is to run `git gc` immediately after the `git clone` and then run `generate_index.ml`

**Comment by samoht** [comment]
Is this a fresh clone? Normally shallow packs are supposed to be used only on `git fetch` (because they reference objects already present on the client than the server decide to not include in the pack to save space). Should not be very hard to fix, I'll look into that.

**Comment by samoht** [comment]
I've pushed a quick fix for this it's untested as I cannot repro. I'll check if I can make a test-case. Please re-open if you still have the issue with a repro.
