### ISSUE TITLE
Fails to install (tests fail to compile)

### ISSUE THREAD

**Issue by talex5** [mirage/ocaml-git#84]
$ make test
    ocaml setup.ml -build 
    W: Cannot find source file matching module 'git' in library git
    Finished, 0 targets (0 cached) in 00:00:00.
    + /home/tal/.opam/profile/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I lib -I lib/http -I lib/unix -I lib/mirage -package alcotest -package cohttp.lwt -package conduit.lwt-unix -package conduit.mirage -package dns.mirage -package dolog -package hex -package io-page -package io-page.unix -package lwt -package lwt.unix -package mirage-flow -package mirage-fs-unix -package mirage-http -package mirage-types.lwt -package mstruct -package nocrypto -package ocamlgraph -package uri -package uri.services -package zip -w A-4-41-44 -I lib_test -I lib -I lib/mirage -I lib/unix -o lib_test/test_common.cmo lib_test/test_common.ml
    File "lib_test/test_common.ml", line 81, characters 7-23:
    Error: Unbound value Pack_index.equal

This broke the CueKeeper build, though I'm not exactly sure why, because CueKeeper doesn't depend on git and I certainly didn't intend to run its tests!

https://travis-ci.org/talex5/cuekeeper/builds/66840028

**Comment by samoht** [comment]
Woops. I think we didn't compile/run the tests until very recently so this has pass though. Sorry about that, I'll make a new release to fix that.

For running the tests: it's indeed annoying, see https://github.com/ocaml/opam/issues/2190
