### ISSUE TITLE
Fails to install on Travis (unit tests fail)

### ISSUE THREAD

**Issue by talex5** [mirage/ocaml-git#91]
The CueKeeper Travis build is failing again due to git not installing:

    #=== ERROR while installing git.1.5.1 =========================================#
    # opam-version 1.2.2
    # os           linux
    # command      make test
    # path         /home/travis/.opam/system/build/git.1.5.1
    # compiler     system (4.02.1)
    # exit-code    2
    # env-file     /home/travis/.opam/system/build/git.1.5.1/git-32779-201c9f.env
    # stdout-file  /home/travis/.opam/system/build/git.1.5.1/git-32779-201c9f.out
    # stderr-file  /home/travis/.opam/system/build/git.1.5.1/git-32779-201c9f.err
    ### stdout ###
    # [...]
    # MIR-FS-mirage  0   Operations on blobs.                                    [OK]
    # MIR-FS-mirage  1   Operations on trees.                                    [OK]
    # MIR-FS-mirage  2   Operations on commits.                                  [OK]
    # MIR-FS-mirage  3   Operations on tags.                                     [OK]
    # MIR-FS-mirage  4   Operations on references.                               [OK]
    # MIR-FS-mirage  5   Operations on index.                                    [OK]
    # MIR-FS-mirage  6   Operations on pack files.                               [OK]
    # MIR-FS-mirage  7   Remote operations.                                    [SKIP]
    # MIR-FS-mirage  8   Resource leaks.                                       [SKIP]
    # 1 error! in 0.701s. 22 tests run.
    ### stderr ###
    # W: Cannot find source file matching module 'git' in library git
    # W: Test 'test_git' fails: Command '/home/travis/.opam/system/build/git.1.5.1/_build/lib_test/test.native -q' terminated with error code 1
    # E: Failure("Tests had a 100.00% failure rate")
    # make: *** [test] Error 1

Any idea what causes this? https://travis-ci.org/talex5/cuekeeper/builds/68780970

**Comment by samoht** [comment]
That's strange...

**Comment by samoht** [comment]
>  W: Cannot find source file matching module 'git' in library git 

actually this is just a warning put by `_oasis` because we are using packing the library (not sure why but well). The unit test itself seems to be raising an exception somewhere, I'm investigating ...

**Comment by samoht** [comment]
I've fixed both alcotest (new release is 0.4.1) and ocaml-git (a new version is on its way: https://github.com/ocaml/opam-repository/pull/4362) which fixes an issue with the index test. Should work better now.
