### ISSUE TITLE
Fatal error: exception Invalid_argument("Hex.to_char: 114 is an invalid char")

### ISSUE THREAD

**Issue by talex5** [mirage/ocaml-git#96]
Got this doing `Store.tags` on an Irmin Git FS. Log shows:

    0.007 unix         INFO : Reading .../.git/refs/remotes/origin/HEAD

This file contains

    ref: refs/remotes/origin/pkg-base-no-ppx

Guess it doesn't like clones of non-bare repos?

**Comment by samoht** [comment]
Yea, non `ocaml-git` doesn't properly supports bare-repository: it just creates a normal `.git` folder but do not populate the filesystem. That error is not very useful though.

**Comment by samoht** [comment]
Seems to work fine on my limited testing.
